spring.application.name=votify
server.port=8085
spring.profiles.active=local

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_UPASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG